language: php

sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

php:
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_install:
  - travis_retry composer self-update --stable -n
  - composer validate --no-check-all --strict

install:
  - travis_retry composer update --prefer-source $COMPOSER_FLAGS
  - travis_retry composer require --dev satooshi/php-coveralls

script:
  - composer run phpunit -- --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
